### ISSUE TITLE
toolkit HCRMI todo

### ISSUE THREAD

**Issue by jfslin** [ORB-HD/rbdl-toolkit#16]
Starting a todo list of things that I think we will need to get Toolkit operating for regular HCRMI use at UW. I will summarize the current conversations regarding each of these issues, and we can create specific issues for them separately as needed. We can change this around as needed. If this should be moved elsewhere, I can do that as well. 

Main goals:
- IK with URDF models
- Improve documentation

- [ ] Get RBDL Toolkit operational on Ubuntu 20.04
  - It sounds like AppImage might not play well on 20.04. This will need further testing
  - #13: "The AppImage was build using Ubuntu 18.04. According to the AppImage documention it should therefor run on anything newer. My Main system at home is using Arch and the it works just fine. But I also have seen previous versions of the toolkit AppImage fail on newer Ubuntu versions. Sadly debugging did not lead to a good explanation for why this happens and also the errors where not reproducible on a different machine with the same base operating system."
  - Slack with @ju6ge: "I would stick to 18.04 as the target for now because Canonical has been changing a lot of stuff in regards to their future vision about their packaging (they are pushing for snap packages). For now I think 18.04 is more stable."
- [ ] Generate basic wireframe on models that does not have explicit mesh information
  - Right now, Toolkit requires some mesh information to exist within the lua/urdf model before it visualizes anything. I think we should create some basic wireframe that draws straight lines between each tree node to serve as some basic visualization in cases that no meshes are found
  - #13: "Okay so the reemc_hd.lua is a valid lua model, but it does not specify any visuals, meaning there is no mesh information in there and therefor rbdl-toolkit has nothing to display"
- [ ] Create documentation on how to load Lua and URDF models @jfslin 
  - Currently, no baseline documentation exists, so any sort of documentation will be helpful
- [ ] Load URDF models, including files created using Gazebo (ie REEM C from Docker) @jfslin 
  - I haven't actually tried this yet, but if it works, it should be added to the Lua/URDF documentation
- [ ] Add ability to define ModelMarkers URDF information into the model via Toolkit @RVSagar
  - Most models will not have ModelMarker information within it, meaning we cannot IK with it
  - Might need to come up with a file format and notation just for this
  - Details: https://github.com/ORB-HD/rbdl-toolkit/issues/14#issuecomment-767840197
- [ ] Add marker names into GUI after a file (or model) is loaded
  - Slack with @ju6ge: "displaying marker names is not part of the code, but i think that would be a lot easier to add … to do that you would need to look into the implementation of the MotionMarkerPlugin, it implements creating the marker scene objects that get attached to the model. Qt3D should have functionalty to display text is some form or another, so you would need to attach a text object to the marker objects that get displayed, maybe even add a setting to enable displaying of the markers."
- [ ] Documentation

**Comment by ju6ge** [comment]
Thanks for the summary and I think having this issue open as a thread might by useful for more general coordination. 

- I will be setting up at ubuntu 20.04 vm to at least find out what is causing the issues.
- Regarding the wireframe:  that should not be to hard because a lot of code is shared already between the urdf and lua model loading code. So I put this up on my priority list.
- Regarding the model markers. There also exists two external plugins for rbdl-toolkit one of which is used to load imu marker positions from a csv file. The code for that is basically exactly what you need to add model markers, except you need to use the ModelMarkerExtention class from the toolkit source. So take a look at that. The plugins can be found on the ORB-HD github page.
- I am very grateful for more documentation from a more use oriented perspective. My main focus has been in the architecture and development of the toolkit and tying to get it running on many systems easily.
